### PR TITLE
Feature cpp nix

### PR DESCRIPTION
**Pull request by Jegp**
Re-introduces CPP tests via nix builds

### CODE REVIEW

**Comment by Jegp** [comment]
Alright, I think this is *finally* ready for a review. Would you mind giving it a look, @emijan-kth?
When it's ready, we'll have completely reproducible builds :smile:

**Review by emijan-kth — CHANGES_REQUESTED** [review]
Good change!

It seems though like there is an issue related to the compilation of flatbuffers. Specifically, I get the following error when trying to build:

```
CMake Error at src/CMakeLists.txt:5 (add_subdirectory):
  add_subdirectory given source
  "/[...]/ae-stream-feature-cpp-nix/src/flatbuffers-build"
  which is not an existing directory.


CMake Error at src/CMakeLists.txt:20 (flatbuffers_generate_headers):
  Unknown CMake command "flatbuffers_generate_headers".

```

**Comment by Jegp** [comment]
That's odd. I tested this both with and without flatbuffers-compiler installed.
Do you already have flatc in your path?

**Review by emijan-kth — CHANGES_REQUESTED** [review]
When building with no flatbuffers installed beforehand, I get build errors like the following:

```

In file included from /usr/include/libcaercpp/devices/davis.hpp:4,
                 from /[...]/aestream-feature-cpp-nix/src/input/inivation.hpp:8,
                 from /[...]/aestream-feature-cpp-nix/src/aestream.cpp:16:
/usr/include/libcaercpp/events/frame.hpp:20:17: fatal error: opencv2/core.hpp: No such file or directory
   20 | #       include <opencv2/core.hpp>
      |                 ^~~~~~~~~~~~~~~~~~
```

I was able to get the build working by adding the following section to `src/CMakeLists.txt`:
```

# OpenCV
find_package (OpenCV 4.0.0 REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
```

**Comment by Jegp** [comment]
OpenCV shouldn't be necessary for libcaer to build (https://gitlab.com/inivation/dv/libcaer/). If you don't have the flag `-DENABLE_OPENCV=1`, it shouldn't be required. Could you check your flags or whether OpenCV is in your path somewhere?

**Review by emijan-kth — APPROVED** [review]
The build error related to OpenCV can also be worked around by adding the following to src/CMakeLists.txt:

`add_definitions(-DLIBCAER_FRAMECPP_OPENCV_INSTALLED=0)`

**Pull request merged**
